//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BooksWebApp.BooksWebServiceProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BooksWithAuthorName", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BooksWithAuthorName : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BookGenreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        private long BookIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string BookTitle {
            get {
                return this.BookTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.BookTitleField, value) != true)) {
                    this.BookTitleField = value;
                    this.RaisePropertyChanged("BookTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string BookGenre {
            get {
                return this.BookGenreField;
            }
            set {
                if ((object.ReferenceEquals(this.BookGenreField, value) != true)) {
                    this.BookGenreField = value;
                    this.RaisePropertyChanged("BookGenre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public long BookId {
            get {
                return this.BookIdField;
            }
            set {
                if ((this.BookIdField.Equals(value) != true)) {
                    this.BookIdField = value;
                    this.RaisePropertyChanged("BookId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long AuthorIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuthorNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long AuthorId {
            get {
                return this.AuthorIdField;
            }
            set {
                if ((this.AuthorIdField.Equals(value) != true)) {
                    this.AuthorIdField = value;
                    this.RaisePropertyChanged("AuthorId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string AuthorName {
            get {
                return this.AuthorNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorNameField, value) != true)) {
                    this.AuthorNameField = value;
                    this.RaisePropertyChanged("AuthorName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BooksWebServiceProxy.BooksWebServiceSoap")]
    public interface BooksWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllBooksWithAuthorsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBooksWithAuthors", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponse GetAllBooksWithAuthors(BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllBooksWithAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponse> GetAllBooksWithAuthorsAsync(BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllAuthorsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAuthors", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponse GetAllAuthors(BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllAuthors", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponse> GetAllAuthorsAsync(BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest request);
        
        // CODEGEN: Generating message contract since element name bookId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOneBookWithAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponse GetOneBookWithAuthor(BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetOneBookWithAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponse> GetOneBookWithAuthorAsync(BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name authorName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.insertAuthorResponse insertAuthor(BooksWebApp.BooksWebServiceProxy.insertAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.insertAuthorResponse> insertAuthorAsync(BooksWebApp.BooksWebServiceProxy.insertAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name authorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.updateAuthorResponse updateAuthor(BooksWebApp.BooksWebServiceProxy.updateAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.updateAuthorResponse> updateAuthorAsync(BooksWebApp.BooksWebServiceProxy.updateAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name bookTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBook", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.InsertBookResponse InsertBook(BooksWebApp.BooksWebServiceProxy.InsertBookRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertBook", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.InsertBookResponse> InsertBookAsync(BooksWebApp.BooksWebServiceProxy.InsertBookRequest request);
        
        // CODEGEN: Generating message contract since element name bookTitle from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBooks", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.updateBooksResponse updateBooks(BooksWebApp.BooksWebServiceProxy.updateBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateBooks", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.updateBooksResponse> updateBooksAsync(BooksWebApp.BooksWebServiceProxy.updateBooksRequest request);
        
        // CODEGEN: Generating message contract since element name getFirstAuthorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFirstAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponse getFirstAuthor(BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFirstAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponse> getFirstAuthorAsync(BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name getLastAuthorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getLastAuthorResponse getLastAuthor(BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getLastAuthorResponse> getLastAuthorAsync(BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name authorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNextAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getNextAuthorResponse getNextAuthor(BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNextAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getNextAuthorResponse> getNextAuthorAsync(BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name authorId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreviousAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponse getPreviousAuthor(BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreviousAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponse> getPreviousAuthorAsync(BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name getFirstBookAndAuthorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFirstBookAndAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponse getFirstBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFirstBookAndAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponse> getFirstBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name getLastBookAndAuthorResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastBookAndAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponse getLastBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getLastBookAndAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponse> getLastBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name bookId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNextBookAndAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponse getNextBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNextBookAndAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponse> getNextBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest request);
        
        // CODEGEN: Generating message contract since element name bookId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreviousBookAndAuthor", ReplyAction="*")]
        BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponse getPreviousBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPreviousBookAndAuthor", ReplyAction="*")]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponse> getPreviousBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksWithAuthorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksWithAuthors", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequestBody Body;
        
        public GetAllBooksWithAuthorsRequest() {
        }
        
        public GetAllBooksWithAuthorsRequest(BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllBooksWithAuthorsRequestBody {
        
        public GetAllBooksWithAuthorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBooksWithAuthorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBooksWithAuthorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponseBody Body;
        
        public GetAllBooksWithAuthorsResponse() {
        }
        
        public GetAllBooksWithAuthorsResponse(BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllBooksWithAuthorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName[] GetAllBooksWithAuthorsResult;
        
        public GetAllBooksWithAuthorsResponseBody() {
        }
        
        public GetAllBooksWithAuthorsResponseBody(BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName[] GetAllBooksWithAuthorsResult) {
            this.GetAllBooksWithAuthorsResult = GetAllBooksWithAuthorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAuthorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAuthors", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequestBody Body;
        
        public GetAllAuthorsRequest() {
        }
        
        public GetAllAuthorsRequest(BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllAuthorsRequestBody {
        
        public GetAllAuthorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllAuthorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllAuthorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponseBody Body;
        
        public GetAllAuthorsResponse() {
        }
        
        public GetAllAuthorsResponse(BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllAuthorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.Author[] GetAllAuthorsResult;
        
        public GetAllAuthorsResponseBody() {
        }
        
        public GetAllAuthorsResponseBody(BooksWebApp.BooksWebServiceProxy.Author[] GetAllAuthorsResult) {
            this.GetAllAuthorsResult = GetAllAuthorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOneBookWithAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOneBookWithAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequestBody Body;
        
        public GetOneBookWithAuthorRequest() {
        }
        
        public GetOneBookWithAuthorRequest(BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOneBookWithAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookId;
        
        public GetOneBookWithAuthorRequestBody() {
        }
        
        public GetOneBookWithAuthorRequestBody(string bookId) {
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetOneBookWithAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetOneBookWithAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponseBody Body;
        
        public GetOneBookWithAuthorResponse() {
        }
        
        public GetOneBookWithAuthorResponse(BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetOneBookWithAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName GetOneBookWithAuthorResult;
        
        public GetOneBookWithAuthorResponseBody() {
        }
        
        public GetOneBookWithAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName GetOneBookWithAuthorResult) {
            this.GetOneBookWithAuthorResult = GetOneBookWithAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.insertAuthorRequestBody Body;
        
        public insertAuthorRequest() {
        }
        
        public insertAuthorRequest(BooksWebApp.BooksWebServiceProxy.insertAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class insertAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorName;
        
        public insertAuthorRequestBody() {
        }
        
        public insertAuthorRequestBody(string authorName) {
            this.authorName = authorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class insertAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="insertAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.insertAuthorResponseBody Body;
        
        public insertAuthorResponse() {
        }
        
        public insertAuthorResponse(BooksWebApp.BooksWebServiceProxy.insertAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class insertAuthorResponseBody {
        
        public insertAuthorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.updateAuthorRequestBody Body;
        
        public updateAuthorRequest() {
        }
        
        public updateAuthorRequest(BooksWebApp.BooksWebServiceProxy.updateAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string authorName;
        
        public updateAuthorRequestBody() {
        }
        
        public updateAuthorRequestBody(string authorId, string authorName) {
            this.authorId = authorId;
            this.authorName = authorName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.updateAuthorResponseBody Body;
        
        public updateAuthorResponse() {
        }
        
        public updateAuthorResponse(BooksWebApp.BooksWebServiceProxy.updateAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateAuthorResponseBody {
        
        public updateAuthorResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBookRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBook", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.InsertBookRequestBody Body;
        
        public InsertBookRequest() {
        }
        
        public InsertBookRequest(BooksWebApp.BooksWebServiceProxy.InsertBookRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertBookRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bookGenre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authorDropdown;
        
        public InsertBookRequestBody() {
        }
        
        public InsertBookRequestBody(string bookTitle, string bookGenre, string authorDropdown) {
            this.bookTitle = bookTitle;
            this.bookGenre = bookGenre;
            this.authorDropdown = authorDropdown;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertBookResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertBookResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.InsertBookResponseBody Body;
        
        public InsertBookResponse() {
        }
        
        public InsertBookResponse(BooksWebApp.BooksWebServiceProxy.InsertBookResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertBookResponseBody {
        
        public InsertBookResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBooks", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.updateBooksRequestBody Body;
        
        public updateBooksRequest() {
        }
        
        public updateBooksRequest(BooksWebApp.BooksWebServiceProxy.updateBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateBooksRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string bookGenre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string authorDropdown;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string bookId;
        
        public updateBooksRequestBody() {
        }
        
        public updateBooksRequestBody(string bookTitle, string bookGenre, string authorDropdown, string bookId) {
            this.bookTitle = bookTitle;
            this.bookGenre = bookGenre;
            this.authorDropdown = authorDropdown;
            this.bookId = bookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.updateBooksResponseBody Body;
        
        public updateBooksResponse() {
        }
        
        public updateBooksResponse(BooksWebApp.BooksWebServiceProxy.updateBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class updateBooksResponseBody {
        
        public updateBooksResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFirstAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFirstAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequestBody Body;
        
        public getFirstAuthorRequest() {
        }
        
        public getFirstAuthorRequest(BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFirstAuthorRequestBody {
        
        public getFirstAuthorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFirstAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFirstAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponseBody Body;
        
        public getFirstAuthorResponse() {
        }
        
        public getFirstAuthorResponse(BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFirstAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.Author getFirstAuthorResult;
        
        public getFirstAuthorResponseBody() {
        }
        
        public getFirstAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.Author getFirstAuthorResult) {
            this.getFirstAuthorResult = getFirstAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getLastAuthorRequestBody Body;
        
        public getLastAuthorRequest() {
        }
        
        public getLastAuthorRequest(BooksWebApp.BooksWebServiceProxy.getLastAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getLastAuthorRequestBody {
        
        public getLastAuthorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getLastAuthorResponseBody Body;
        
        public getLastAuthorResponse() {
        }
        
        public getLastAuthorResponse(BooksWebApp.BooksWebServiceProxy.getLastAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLastAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.Author getLastAuthorResult;
        
        public getLastAuthorResponseBody() {
        }
        
        public getLastAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.Author getLastAuthorResult) {
            this.getLastAuthorResult = getLastAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getNextAuthorRequestBody Body;
        
        public getNextAuthorRequest() {
        }
        
        public getNextAuthorRequest(BooksWebApp.BooksWebServiceProxy.getNextAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string maxAuthorId;
        
        public getNextAuthorRequestBody() {
        }
        
        public getNextAuthorRequestBody(string authorId, string maxAuthorId) {
            this.authorId = authorId;
            this.maxAuthorId = maxAuthorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getNextAuthorResponseBody Body;
        
        public getNextAuthorResponse() {
        }
        
        public getNextAuthorResponse(BooksWebApp.BooksWebServiceProxy.getNextAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.Author getNextAuthorResult;
        
        public getNextAuthorResponseBody() {
        }
        
        public getNextAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.Author getNextAuthorResult) {
            this.getNextAuthorResult = getNextAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreviousAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreviousAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequestBody Body;
        
        public getPreviousAuthorRequest() {
        }
        
        public getPreviousAuthorRequest(BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreviousAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string authorId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string minAuthorId;
        
        public getPreviousAuthorRequestBody() {
        }
        
        public getPreviousAuthorRequestBody(string authorId, string minAuthorId) {
            this.authorId = authorId;
            this.minAuthorId = minAuthorId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreviousAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreviousAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponseBody Body;
        
        public getPreviousAuthorResponse() {
        }
        
        public getPreviousAuthorResponse(BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreviousAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.Author getPreviousAuthorResult;
        
        public getPreviousAuthorResponseBody() {
        }
        
        public getPreviousAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.Author getPreviousAuthorResult) {
            this.getPreviousAuthorResult = getPreviousAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFirstBookAndAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFirstBookAndAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequestBody Body;
        
        public getFirstBookAndAuthorRequest() {
        }
        
        public getFirstBookAndAuthorRequest(BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFirstBookAndAuthorRequestBody {
        
        public getFirstBookAndAuthorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFirstBookAndAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFirstBookAndAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponseBody Body;
        
        public getFirstBookAndAuthorResponse() {
        }
        
        public getFirstBookAndAuthorResponse(BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFirstBookAndAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getFirstBookAndAuthorResult;
        
        public getFirstBookAndAuthorResponseBody() {
        }
        
        public getFirstBookAndAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getFirstBookAndAuthorResult) {
            this.getFirstBookAndAuthorResult = getFirstBookAndAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastBookAndAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastBookAndAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequestBody Body;
        
        public getLastBookAndAuthorRequest() {
        }
        
        public getLastBookAndAuthorRequest(BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getLastBookAndAuthorRequestBody {
        
        public getLastBookAndAuthorRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLastBookAndAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getLastBookAndAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponseBody Body;
        
        public getLastBookAndAuthorResponse() {
        }
        
        public getLastBookAndAuthorResponse(BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getLastBookAndAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getLastBookAndAuthorResult;
        
        public getLastBookAndAuthorResponseBody() {
        }
        
        public getLastBookAndAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getLastBookAndAuthorResult) {
            this.getLastBookAndAuthorResult = getLastBookAndAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextBookAndAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextBookAndAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequestBody Body;
        
        public getNextBookAndAuthorRequest() {
        }
        
        public getNextBookAndAuthorRequest(BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextBookAndAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string maxBookId;
        
        public getNextBookAndAuthorRequestBody() {
        }
        
        public getNextBookAndAuthorRequestBody(string bookId, string maxBookId) {
            this.bookId = bookId;
            this.maxBookId = maxBookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNextBookAndAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNextBookAndAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponseBody Body;
        
        public getNextBookAndAuthorResponse() {
        }
        
        public getNextBookAndAuthorResponse(BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNextBookAndAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getNextBookAndAuthorResult;
        
        public getNextBookAndAuthorResponseBody() {
        }
        
        public getNextBookAndAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getNextBookAndAuthorResult) {
            this.getNextBookAndAuthorResult = getNextBookAndAuthorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreviousBookAndAuthorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreviousBookAndAuthor", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequestBody Body;
        
        public getPreviousBookAndAuthorRequest() {
        }
        
        public getPreviousBookAndAuthorRequest(BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreviousBookAndAuthorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string minBookId;
        
        public getPreviousBookAndAuthorRequestBody() {
        }
        
        public getPreviousBookAndAuthorRequestBody(string bookId, string minBookId) {
            this.bookId = bookId;
            this.minBookId = minBookId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPreviousBookAndAuthorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPreviousBookAndAuthorResponse", Namespace="http://tempuri.org/", Order=0)]
        public BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponseBody Body;
        
        public getPreviousBookAndAuthorResponse() {
        }
        
        public getPreviousBookAndAuthorResponse(BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPreviousBookAndAuthorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getPreviousBookAndAuthorResult;
        
        public getPreviousBookAndAuthorResponseBody() {
        }
        
        public getPreviousBookAndAuthorResponseBody(BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getPreviousBookAndAuthorResult) {
            this.getPreviousBookAndAuthorResult = getPreviousBookAndAuthorResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BooksWebServiceSoapChannel : BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BooksWebServiceSoapClient : System.ServiceModel.ClientBase<BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap>, BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap {
        
        public BooksWebServiceSoapClient() {
        }
        
        public BooksWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BooksWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BooksWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.GetAllBooksWithAuthors(BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest request) {
            return base.Channel.GetAllBooksWithAuthors(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName[] GetAllBooksWithAuthors() {
            BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest inValue = new BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequestBody();
            BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).GetAllBooksWithAuthors(inValue);
            return retVal.Body.GetAllBooksWithAuthorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.GetAllBooksWithAuthorsAsync(BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest request) {
            return base.Channel.GetAllBooksWithAuthorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsResponse> GetAllBooksWithAuthorsAsync() {
            BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest inValue = new BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.GetAllBooksWithAuthorsRequestBody();
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).GetAllBooksWithAuthorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.GetAllAuthors(BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest request) {
            return base.Channel.GetAllAuthors(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.Author[] GetAllAuthors() {
            BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest inValue = new BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequestBody();
            BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).GetAllAuthors(inValue);
            return retVal.Body.GetAllAuthorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.GetAllAuthorsAsync(BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest request) {
            return base.Channel.GetAllAuthorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetAllAuthorsResponse> GetAllAuthorsAsync() {
            BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest inValue = new BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.GetAllAuthorsRequestBody();
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).GetAllAuthorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.GetOneBookWithAuthor(BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest request) {
            return base.Channel.GetOneBookWithAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName GetOneBookWithAuthor(string bookId) {
            BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequestBody();
            inValue.Body.bookId = bookId;
            BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).GetOneBookWithAuthor(inValue);
            return retVal.Body.GetOneBookWithAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.GetOneBookWithAuthorAsync(BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest request) {
            return base.Channel.GetOneBookWithAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorResponse> GetOneBookWithAuthorAsync(string bookId) {
            BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.GetOneBookWithAuthorRequestBody();
            inValue.Body.bookId = bookId;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).GetOneBookWithAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.insertAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.insertAuthor(BooksWebApp.BooksWebServiceProxy.insertAuthorRequest request) {
            return base.Channel.insertAuthor(request);
        }
        
        public void insertAuthor(string authorName) {
            BooksWebApp.BooksWebServiceProxy.insertAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.insertAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.insertAuthorRequestBody();
            inValue.Body.authorName = authorName;
            BooksWebApp.BooksWebServiceProxy.insertAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).insertAuthor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.insertAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.insertAuthorAsync(BooksWebApp.BooksWebServiceProxy.insertAuthorRequest request) {
            return base.Channel.insertAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.insertAuthorResponse> insertAuthorAsync(string authorName) {
            BooksWebApp.BooksWebServiceProxy.insertAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.insertAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.insertAuthorRequestBody();
            inValue.Body.authorName = authorName;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).insertAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.updateAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.updateAuthor(BooksWebApp.BooksWebServiceProxy.updateAuthorRequest request) {
            return base.Channel.updateAuthor(request);
        }
        
        public void updateAuthor(string authorId, string authorName) {
            BooksWebApp.BooksWebServiceProxy.updateAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.updateAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.updateAuthorRequestBody();
            inValue.Body.authorId = authorId;
            inValue.Body.authorName = authorName;
            BooksWebApp.BooksWebServiceProxy.updateAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).updateAuthor(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.updateAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.updateAuthorAsync(BooksWebApp.BooksWebServiceProxy.updateAuthorRequest request) {
            return base.Channel.updateAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.updateAuthorResponse> updateAuthorAsync(string authorId, string authorName) {
            BooksWebApp.BooksWebServiceProxy.updateAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.updateAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.updateAuthorRequestBody();
            inValue.Body.authorId = authorId;
            inValue.Body.authorName = authorName;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).updateAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.InsertBookResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.InsertBook(BooksWebApp.BooksWebServiceProxy.InsertBookRequest request) {
            return base.Channel.InsertBook(request);
        }
        
        public void InsertBook(string bookTitle, string bookGenre, string authorDropdown) {
            BooksWebApp.BooksWebServiceProxy.InsertBookRequest inValue = new BooksWebApp.BooksWebServiceProxy.InsertBookRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.InsertBookRequestBody();
            inValue.Body.bookTitle = bookTitle;
            inValue.Body.bookGenre = bookGenre;
            inValue.Body.authorDropdown = authorDropdown;
            BooksWebApp.BooksWebServiceProxy.InsertBookResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).InsertBook(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.InsertBookResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.InsertBookAsync(BooksWebApp.BooksWebServiceProxy.InsertBookRequest request) {
            return base.Channel.InsertBookAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.InsertBookResponse> InsertBookAsync(string bookTitle, string bookGenre, string authorDropdown) {
            BooksWebApp.BooksWebServiceProxy.InsertBookRequest inValue = new BooksWebApp.BooksWebServiceProxy.InsertBookRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.InsertBookRequestBody();
            inValue.Body.bookTitle = bookTitle;
            inValue.Body.bookGenre = bookGenre;
            inValue.Body.authorDropdown = authorDropdown;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).InsertBookAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.updateBooksResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.updateBooks(BooksWebApp.BooksWebServiceProxy.updateBooksRequest request) {
            return base.Channel.updateBooks(request);
        }
        
        public void updateBooks(string bookTitle, string bookGenre, string authorDropdown, string bookId) {
            BooksWebApp.BooksWebServiceProxy.updateBooksRequest inValue = new BooksWebApp.BooksWebServiceProxy.updateBooksRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.updateBooksRequestBody();
            inValue.Body.bookTitle = bookTitle;
            inValue.Body.bookGenre = bookGenre;
            inValue.Body.authorDropdown = authorDropdown;
            inValue.Body.bookId = bookId;
            BooksWebApp.BooksWebServiceProxy.updateBooksResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).updateBooks(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.updateBooksResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.updateBooksAsync(BooksWebApp.BooksWebServiceProxy.updateBooksRequest request) {
            return base.Channel.updateBooksAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.updateBooksResponse> updateBooksAsync(string bookTitle, string bookGenre, string authorDropdown, string bookId) {
            BooksWebApp.BooksWebServiceProxy.updateBooksRequest inValue = new BooksWebApp.BooksWebServiceProxy.updateBooksRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.updateBooksRequestBody();
            inValue.Body.bookTitle = bookTitle;
            inValue.Body.bookGenre = bookGenre;
            inValue.Body.authorDropdown = authorDropdown;
            inValue.Body.bookId = bookId;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).updateBooksAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getFirstAuthor(BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest request) {
            return base.Channel.getFirstAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.Author getFirstAuthor() {
            BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequestBody();
            BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getFirstAuthor(inValue);
            return retVal.Body.getFirstAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getFirstAuthorAsync(BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest request) {
            return base.Channel.getFirstAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getFirstAuthorResponse> getFirstAuthorAsync() {
            BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getFirstAuthorRequestBody();
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getFirstAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getLastAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getLastAuthor(BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest request) {
            return base.Channel.getLastAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.Author getLastAuthor() {
            BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getLastAuthorRequestBody();
            BooksWebApp.BooksWebServiceProxy.getLastAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getLastAuthor(inValue);
            return retVal.Body.getLastAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getLastAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getLastAuthorAsync(BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest request) {
            return base.Channel.getLastAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getLastAuthorResponse> getLastAuthorAsync() {
            BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getLastAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getLastAuthorRequestBody();
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getLastAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getNextAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getNextAuthor(BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest request) {
            return base.Channel.getNextAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.Author getNextAuthor(string authorId, string maxAuthorId) {
            BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getNextAuthorRequestBody();
            inValue.Body.authorId = authorId;
            inValue.Body.maxAuthorId = maxAuthorId;
            BooksWebApp.BooksWebServiceProxy.getNextAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getNextAuthor(inValue);
            return retVal.Body.getNextAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getNextAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getNextAuthorAsync(BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest request) {
            return base.Channel.getNextAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getNextAuthorResponse> getNextAuthorAsync(string authorId, string maxAuthorId) {
            BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getNextAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getNextAuthorRequestBody();
            inValue.Body.authorId = authorId;
            inValue.Body.maxAuthorId = maxAuthorId;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getNextAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getPreviousAuthor(BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest request) {
            return base.Channel.getPreviousAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.Author getPreviousAuthor(string authorId, string minAuthorId) {
            BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequestBody();
            inValue.Body.authorId = authorId;
            inValue.Body.minAuthorId = minAuthorId;
            BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getPreviousAuthor(inValue);
            return retVal.Body.getPreviousAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getPreviousAuthorAsync(BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest request) {
            return base.Channel.getPreviousAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getPreviousAuthorResponse> getPreviousAuthorAsync(string authorId, string minAuthorId) {
            BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getPreviousAuthorRequestBody();
            inValue.Body.authorId = authorId;
            inValue.Body.minAuthorId = minAuthorId;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getPreviousAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getFirstBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest request) {
            return base.Channel.getFirstBookAndAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getFirstBookAndAuthor() {
            BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequestBody();
            BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getFirstBookAndAuthor(inValue);
            return retVal.Body.getFirstBookAndAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getFirstBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest request) {
            return base.Channel.getFirstBookAndAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorResponse> getFirstBookAndAuthorAsync() {
            BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getFirstBookAndAuthorRequestBody();
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getFirstBookAndAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getLastBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest request) {
            return base.Channel.getLastBookAndAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getLastBookAndAuthor() {
            BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequestBody();
            BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getLastBookAndAuthor(inValue);
            return retVal.Body.getLastBookAndAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getLastBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest request) {
            return base.Channel.getLastBookAndAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorResponse> getLastBookAndAuthorAsync() {
            BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getLastBookAndAuthorRequestBody();
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getLastBookAndAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getNextBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest request) {
            return base.Channel.getNextBookAndAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getNextBookAndAuthor(string bookId, string maxBookId) {
            BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.maxBookId = maxBookId;
            BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getNextBookAndAuthor(inValue);
            return retVal.Body.getNextBookAndAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getNextBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest request) {
            return base.Channel.getNextBookAndAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorResponse> getNextBookAndAuthorAsync(string bookId, string maxBookId) {
            BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getNextBookAndAuthorRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.maxBookId = maxBookId;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getNextBookAndAuthorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponse BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getPreviousBookAndAuthor(BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest request) {
            return base.Channel.getPreviousBookAndAuthor(request);
        }
        
        public BooksWebApp.BooksWebServiceProxy.BooksWithAuthorName getPreviousBookAndAuthor(string bookId, string minBookId) {
            BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.minBookId = minBookId;
            BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponse retVal = ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getPreviousBookAndAuthor(inValue);
            return retVal.Body.getPreviousBookAndAuthorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponse> BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap.getPreviousBookAndAuthorAsync(BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest request) {
            return base.Channel.getPreviousBookAndAuthorAsync(request);
        }
        
        public System.Threading.Tasks.Task<BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorResponse> getPreviousBookAndAuthorAsync(string bookId, string minBookId) {
            BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest inValue = new BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequest();
            inValue.Body = new BooksWebApp.BooksWebServiceProxy.getPreviousBookAndAuthorRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.minBookId = minBookId;
            return ((BooksWebApp.BooksWebServiceProxy.BooksWebServiceSoap)(this)).getPreviousBookAndAuthorAsync(inValue);
        }
    }
}
